# GENERATING RANDOM NUMBERS WITH NumPy

In [3]:
# Import needed packages:
import numpy as np

In [4]:
# Generate a random number from the normal distribution:
np.random.normal()

0.3384979507413384

In [5]:
# Generate 5 random numbers from the nomal distribution:
np.random.normal(size=5)


array([ 0.5777366 , -0.36413627, -0.31910044,  0.69283832, -0.4559127 ])

In [6]:
# Generate 3 random numbers from the uniform distribution:
np.random.uniform(size= 3)

array([0.8013052 , 0.53913396, 0.67889184])

In [8]:
# Generate 4 random integers between 100 and 1000
np.random.randint(low=150, high=850, size=4)

array([791, 379, 703, 530])

In [9]:
# Generate 4 random integers between 100 and 1000
np.random.randint(low=150, high=850, size=4)

array([673, 299, 472, 328])

In [10]:
# Generate 4 random integers between 100 and 1000
np.random.randint(low=150, high=850, size=4)

array([827, 839, 364, 797])